pull_request_rules:
  - name: Automatic merge on bot
    conditions:
          - author=imgbot[bot]
    actions:
      merge:
        method: merge

  - name: Automatic merge on admins
    conditions:
        - or:
          - author=StephanAkkerman
          - author=TimKoornstra
    actions:
      merge:
        method: merge
