[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88
profile = "black"

[tool.ruff]
line-length = 88
#select = ["I001"]

[tool.ruff.lint.pydocstyle]
# Use Google-style docstrings.
convention = "numpy"
